const express = require('express');
const auth = require('../middlewares/authMiddleware');
const roles = require('../middlewares/roleMiddleware');
const controller = require('../controllers/orderController');
const router = express.Router();
router.use(auth);
router.get('/', controller.list);
router.post('/', roles('customer', 'seller', 'admin', 'user'), controller.create);
router.patch('/:id/status', roles('seller', 'admin'), controller.updateStatus);
module.exports = router;